apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ai-demographic-hpa
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-demographic-deployment
  targetCPUUtilizationPercentage: 70