# Generated by Django 5.0.2 on 2024-03-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='elementCustomerServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('dress', models.IntegerField()),
                ('tShirt', models.IntegerField()),
                ('jacket', models.IntegerField()),
                ('top', models.IntegerField()),
                ('longSleeve', models.IntegerField()),
                ('short', models.IntegerField()),
                ('skirt', models.IntegerField()),
                ('trouser', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Unknown', 'U')], default='Unknown', max_length=7)),
                ('time', models.DateField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='predictImageServiceModel',
        ),
    ]
