# Generated by Django 5.0.2 on 2024-03-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_elementcustomerservicemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementcustomerservicemodel',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
