# Generated by Django 5.0.2 on 2024-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_elementcustomerservicemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementcustomerservicemodel',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
