# Generated by Django 5.0.2 on 2024-03-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_elementcustomerservicemodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementcustomerservicemodel',
            name='age',
            field=models.CharField(choices=[('15-29', '15-29'), ('30-59', '30-59'), ('60up', '60up'), ('Unknown', 'Unknown')], default='Unknown', max_length=7),
        ),
    ]
