# Generated by Django 5.0.2 on 2024-03-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_elementcustomerservicemodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementcustomerservicemodel',
            name='final_bottom',
            field=models.CharField(choices=[('short', 'short'), ('skirt', 'skirt'), ('trouser', 'trouser')], default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='elementcustomerservicemodel',
            name='final_top',
            field=models.CharField(choices=[('dress', 'dress'), ('t-shirt', 'tShirt'), ('jacket', 'jacket'), ('top', 'top'), ('long-sleeve', 'longSleeve')], default='Unknown', max_length=20),
        ),
    ]
