# Generated by Django 5.0.2 on 2024-03-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_elementcustomerservicemodel_final_bottom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementcustomerservicemodel',
            old_name='final_top',
            new_name='finalTop',
        ),
        migrations.RemoveField(
            model_name='elementcustomerservicemodel',
            name='final_bottom',
        ),
        migrations.AddField(
            model_name='elementcustomerservicemodel',
            name='finalBottom',
            field=models.CharField(choices=[('short', 'short'), ('skirt', 'skirt'), ('trouser', 'trouser'), ('None', 'None')], default='Unknown', max_length=20),
        ),
    ]
