# Generated by Django 5.0.2 on 2024-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_rename_final_top_elementcustomerservicemodel_finaltop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementcustomerservicemodel',
            name='image',
            field=models.ImageField(default='null', upload_to='images/'),
        ),
    ]
