# Generated by Django 5.0.2 on 2024-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_elementcustomerservicemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementcustomerservicemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
